---
title: "HW 1"
author: "Claudia Lo"
date: "2/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#Create a function  called "count_func" that accepts two arguments, a string and a vector of string. 
#It returns the count of the number of occurrences of the string in the input vector.(Give a few examples)
x<-c("a","b","a")

count_func<-function(string,x){
  count<-0
  for(ele in x){
    if (ele==string){
      count <- count+1
    }
  }
  return(count)
}
print(count_func("b",c("a","b","c")))
print(count_func("d",c("a","b","c","a")))
```

```{r}
# Write a function called "get_min" that uses if,else if, and else statements to print the min element in a numeric vector with 3 elements.
x<-c(5,2,3)
get_min<-function(x){
  if(x[1]<x[2]& x[1]<x[3]){
   abc<-x[1]
  }else if(x[2]<x[3]){
    abc<-x[2]
  }
  else{
    abc<-x[3]
  }
  return(abc)
} 
print(get_min(x))
```

```{r}
# Create a function called "get_even_odd" that accepts an integer and will tell you if it is odd or even.
num<-6
get_even_odd<-function(num)
  if(num%%2==0){
    print('Even')
  }else{
    print("Odd")
  }
get_even_odd(6)
get_even_odd(7)
get_even_odd(-3)
```

```{r}
#Recreate the following dataframe by creating vectors and using the data.frame function:
A<-c("a","b","c")
B<-c(1,2,3)
C<-c(TRUE,FALSE,TRUE)
df<-data.frame(A,B,C)
df
```

```{r}
# Install and activate "nycflights13" package.
#install.packages('nycflights13')
library(nycflights13)
```

```{r}
# print top rows (head) of the flights dataset and answer the following questions:
head(flights)
```

```{r}
# How many rows and columns are in the dataset
nrow(flights)
ncol(flights)
```

```{r}
# How many years we have data for in the dataset?
table(flights$year)
head(flights$year)
flights$year[2013]
```

```{r}
# what are the number of flights in each month
table(flights$month)
```

```{r}
# does it contain any missing values?
any(is.na(flights))
any(is.na(flights$month))
```

```{r}
# select the rows that are at the last days of the months (day 30 or 31). Print top 6 rows (head).
sub1<-subset(flights,subset=day>=30)
head(sub1)
```

```{r}
# What is the average of 'dep_time'
mean(flights$dep_time,na.rm=T)
```

```{r}
# select only columns of: "year", "month", "day", "carrier", "origin", "dest" . Print the head.
sub2<-flights[c("year", "month", "day", "carrier", "origin", "dest")]
sub2
head(sub2)
```

